# named list of all robots
fileversion: 3

robots:
  cf231:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E7
    initial_position: [0.0, 1.15, 0.0]
    type: cf21_lighthouse

robot_types:
  cf21_lighthouse:
    motion_capture:
      tracking: "vendor"
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 10
      odom:
        frequency: 10
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 2
  reference_frame: "world"
  broadcasts:
    num_repeats: 15
    delay_between_repeats_ms: 1
